---
title: "Artificial Neural Networks"
subtitle: In class activities
date: 2023-09-10
format:
  pdf
date-modified: 2024-09-09
resources:
  - ./ann_single_layer_perceptron.mlx
  - ./ann_crystallizer_model_for_training.slx
  - ./ann_crystallizer_model_control.slx
---

## Activities

### Single-layer perceptron neural network

In a chemical processing plant, a critical valve is controlled based on three
parameters: temperature, pressure, and reactant concentration, all within
normalized ranges. Each parameter is represented as a binary input: 1 if the
parameter is within the desired range, indicating favorable conditions for
opening the valve, and 0 if it is outside the range, indicating unfavorable
conditions. The decision to open the valve depends on these inputs to ensure
safe and efficient operation.


- Scenario 1: Low temperature, low pressure, optimal concentration.
- Scenario 2: Optimal temperature, optimal pressure, optimal concentration.
- Scenario 3: Optimal temperature, low pressure, optimal concentration.
- Scenario 4: Low temperature, optimal pressure, optimal concentration.

: Expected valve position 

| Temperature | Pressure  | Concentration | Valve Opens |
|-|-|-|-|
| 0 | 0 | 1 | 0 |
| 1 | 1 | 1 | 1 |
| 1 | 0 | 1 | 1 |
| 0 | 1 | 1 | 0 |

Design a simple single-layer perceptron using MATLAB to learn this
decision-making process based on the input parameters.

::: {.callout-tip collapse="true"}
## Solution

The code for single layer perceptron is in [ann_single_layer_perceptron.mlx](./ann_single_layer_perceptron.mlx).

:::

### ANN modeling of Crystallization

To control the average crystal size in a crystallization process, it is
essential to account for its dependence on two measurable variables:
 
1. Mother liquor temperature $T$
2. Mother liquor density $\rho$

Since average crystal size cannot be directly measured and requires offline
laboratory analysis, there are inherent delays in controlling the crystallizer.

To predict crystal size using temperature $T$ and density $\rho$, consider the
following:

1. Input transfer functions

	a. Feed flow rate (U~1~)

	$$ U_1(s) = \frac{1}{s + 1} $${#eq-1}

	b. Stirrer Speed (U~2~)
	
	$$ U_2(s) = \frac{1}{2 s + 1} $${#eq-2}
		
2. Process Transfer functions

	a. Temperature (X~1~) is influenced by U~1~
	
	$$ X_1(s) = \left( \frac{2}{ 3 s + 1} + \frac{ - 0.2 }{ 2 s^2 + 1.1 s + 1}
	\right) e^{-s} $${#eq-3}
		
	b. Density (X~2~) is influenced by U~2~
	
	$$ X_2(s) = \frac{ e^{-s}}{ 4 s^2 + 3 s + 1} $${#eq-4}
		
3. Dependency of average crystal size d~avg~ (Y) on temperature and density is given by

$$ d_{avg} = 10 + (0.8 T + 1.3 \rho + 1.1 T^2 - 1.9 \rho^2 + 0.6 T \rho) $${#eq-5}

Develop an Artificial Neural Network (ANN) model to predict the average crystal
size in a crystallization process based on measured temperature and density,
which are influenced by feed flow rate and stirrer speed.

::: {.callout-tip collapse="true"}
## Solution

* [Crystallizer model for training](./ann_crystallizer_model_for_training.slx)
* [Crystallizer model control](./ann_crystallizer_model_control.slx)

:::


