---
title: "Modeling and control of solid oxide electrolysis cells for green
        hydrogen production using machine learning" 
subtitle: CHEN4011 Final Project - Semester 2, 2024
author: ""
date-modified: 2024-08-27
format:
  pdf
resources:
  - ./1-s2.0-S2666952824000347-mmc1.pdf
  - ./yang_2024_machine_learning-assisted_prediction_and_optimization_of_solid_oxide.pdf
---

::: {.content-visible when-format="pdf"}

|                             |                                      |
| -                           | -                                    |
| **Due Date**:                   | 2024-10-24                        |
| **Time**:                   | midnight                        |
| **Number of group members**:    | 4 |
| **Total marks**: | 100                                   |

:::

## Instructions

1. The project is conducted in a group of four. You are free to choose your
   group.
3. Please notify the instructors of your groups as soon as you form them.
4. If you cannot find a group, please get in touch with your instructor at the earliest.
5. You will need to submit all the files created electronically on blackboard.
6. There should be one submission per group. 
7. Please follow the instructions given below carefully for preparing the files
   for submission. Failure to follow these instructions may result in us not
   being able to assess the files.

   You will be uploading two files.

   1. Report (pdf file containing the report). You need to name the file as
      STUDENTID_CHEN4011_project_report.pdf (Replace STUDENTID with your
      Student ID). You need to make only one submission per group.

   2. Create a zip file named STUDENTID_CHEN4011_project_Supporting_files.zip.
      The zip file should contain a) All supporting files for modeling,
      simulation, and control activities (matlab, simulink) b) the PDF report
      file. You may upload the supporting file to a cloud storage of your
      preference and share a link.

{{< pagebreak >}}

## Problem description

Globally, the primary contributors to greenhouse gas emissions are sectors like
transportation, electricity production, and industrial activities. Green
hydrogen, generated through water electrolysis using renewable energy, is
increasingly seen as a viable option to reduce carbon emissions in
high-energy-demand sectors such as aviation and industrial manufacturing. While
the majority of hydrogen is currently derived from natural gas reforming, a
process that emits greenhouse gases, the focus is shifting towards the scalable
and cost-effective production of green hydrogen. 

Alkaline electrolysis (AEC), proton exchange membrane electrolysis (PEMEC), and
solid oxide electrolysis cell (SOEC) technologies are the three main methods
for green hydrogen production. Of these, SOECs show promise as they can save
more than 30% of electricity consumption compared to AEC and PEMEC when coupled
with low-grade waste heat such as steel metallurgy, chemical industry, and
nuclear power. In addition, the SOEC system adopts a modular design, which is
easy to install and can flexibly adjust the hydrogen production scale according
to actual needs. 

In this project, you will apply machine learning to predict the performance of
a SOEC, and develop control strategies suitable for its effective control.

The insights derived from the model will be used to make data-driven
recommendations about the operations and control of SOECs. 

## Suggested steps

1. Review existing literature on data driven modeling of SOECs. Prepare a brief
   literature review summarizing your findings. 

2. Use the data presented by [@yang2024gce] to develop an artificial neural
   network (ANN) model. The paper is provided
[here](./yang_2024_machine_learning-assisted_prediction_and_optimization_of_solid_oxide.pdf).
The data is available in a [pdf file](./1-s2.0-S2666952824000347-mmc1.pdf).

3. The model should consider all the features provided in the data and use them
   to predict $\ce{H2}$ production rate. 

4. Divide the available data in training data and testing data. Using the
   testing data, compare the model's performance. 

5. For the SOEC system, identify control, manipulated, and disturbance
   variables. Propose and evaluate appropriate control strategies. 

6. For a given control strategy, develop appropriate transfer function using
   the ANN model. Use this transfer function to test the controller
   performance. The models could be SISO or MIMO models. 

## Report

Prepare a report consisting of the following:

1. Data driven modeling of SOECs (20 marks): 
   Present a comprehensive note (5 – 6 pages) on the state of the art of use of
   data driven modeling for design, control, and optimization of SOECs for
   hydrogen production.
2. ANN model of a SOEC (40 marks): 
2. Control strategy for SOEC (20 marks)
3. Critical review (10 marks)
   Present a critical review of your modeling and control activity.
   Some key guiding questions (not limited to) are: 
   Why should we believe your simulations?
   What worked, What did not work?
   How to improve the simulations?


## Marking

The report will be marked as follows:

| Description                                                                    | Marks |
| ------------------------------------------------------------------------------ | ----- |
| Part 1: | 20 |
| Short note: data driven modeling of SOECs ||
| ||
| Part 2: ANN model of SOECs |30|
|||
| Part 3: Control of SOECs |30|
|||
| Critical Review |10 |
|||
| Report Presentation                                                            | 10     |
|                                                                                |       |
| _Total_                                                                        | 100    |

## References

